// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS3UMU2BOdnldrGtQVEiAZrDD00tBAjgk',
    appId: '1:590438440189:web:23c47c25fb24996e0df294',
    messagingSenderId: '590438440189',
    projectId: 'apple-match',
    authDomain: 'apple-match.firebaseapp.com',
    storageBucket: 'apple-match.appspot.com',
    measurementId: 'G-RT11GZWC0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjACTBNEXTdIz3E7ZZFbnY0Qea4F-L6oU',
    appId: '1:590438440189:android:9bbe812c925e00070df294',
    messagingSenderId: '590438440189',
    projectId: 'apple-match',
    storageBucket: 'apple-match.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpLMPJY9a5pV0nx90f6YlyJz-cmlP471w',
    appId: '1:590438440189:ios:48d602471ccf9d770df294',
    messagingSenderId: '590438440189',
    projectId: 'apple-match',
    storageBucket: 'apple-match.appspot.com',
    iosBundleId: 'com.applematch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpLMPJY9a5pV0nx90f6YlyJz-cmlP471w',
    appId: '1:590438440189:ios:41eb15c3c5735acc0df294',
    messagingSenderId: '590438440189',
    projectId: 'apple-match',
    storageBucket: 'apple-match.appspot.com',
    iosBundleId: 'com.applematch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS3UMU2BOdnldrGtQVEiAZrDD00tBAjgk',
    appId: '1:590438440189:web:b19a08184dd026710df294',
    messagingSenderId: '590438440189',
    projectId: 'apple-match',
    authDomain: 'apple-match.firebaseapp.com',
    storageBucket: 'apple-match.appspot.com',
    measurementId: 'G-2R6RPKWVHX',
  );
}
